"use strict";

const team = require("../models/team");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("tracks", [
      {
        track_id: 1,
        gp_name: "FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024",
        track_name: "Bahrain International Circuit",
        country: "Bahrain",
        city: "Sakhir",
        circuit_length: 5.412,
        first_gp: 2004,
        date_of_gp: new Date("2024-03-02"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 2,
        gp_name: "FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2024",
        track_name: "Jeddah Corniche Circuit",
        country: "Saudi Arabia",
        city: "Jeddah",
        circuit_length: 6.175,
        first_gp: 2021,
        date_of_gp: new Date("2024-03-09"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 3,
        gp_name: "FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2024",
        track_name: "Albert Park Circuit",
        country: "Australia",
        city: "Melbourne",
        circuit_length: 5.303,
        first_gp: 1985,
        date_of_gp: new Date("2024-03-24"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 4,
        gp_name: "FORMULA 1 MSC CRUISES JAPANESE GRAND PRIX 2024",
        track_name: "Suzuka International Racing Course",
        country: "Japan",
        city: "Suzuka",
        circuit_length: 5.807,
        first_gp: 1987,
        date_of_gp: new Date("2024-04-07"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 5,
        gp_name: "FORMULA 1 LENOVO CHINESE GRAND PRIX 2024",
        track_name: "Shanghai International Circuit",
        country: "China",
        city: "Shanghai",
        circuit_length: 5.451,
        first_gp: 2004,
        date_of_gp: new Date("2024-04-21"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 6,
        gp_name: "FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2024",
        track_name: "Miami International Autodrome",
        country: "United States",
        city: "Miami",
        circuit_length: 5.41,
        first_gp: 2024,
        date_of_gp: new Date("2024-05-05"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 7,
        gp_name:
          "FORMULA 1 MSC CRUISES GRAN PREMIO DEL MADE IN ITALY E DELL'EMILIA-ROMAGNA 2024",
        track_name: "Autodromo Enzo e Dino Ferrari",
        country: "Italy",
        city: "Imola",
        circuit_length: 4.959,
        first_gp: 1980,
        date_of_gp: new Date("2024-05-19"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 8,
        gp_name: "FORMULA 1 GRAND PRIX DE MONACO 2024",
        track_name: "Circuit de Monaco",
        country: "Monaco",
        city: "Monte Carlo",
        circuit_length: 3.337,
        first_gp: 1929,
        date_of_gp: new Date("2024-05-26"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 9,
        gp_name: "FORMULA 1 AWS GRAND PRIX DU CANADA 2024",
        track_name: "Circuit Gilles-Villeneuve",
        country: "Canada",
        city: "Montreal",
        circuit_length: 4.361,
        first_gp: 1961,
        date_of_gp: new Date("2024-06-09"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 10,
        gp_name: "FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2024",
        track_name: "Circuit de Barcelona-Catalunya",
        country: "Spain",
        city: "Barcelona",
        circuit_length: 4.675,
        first_gp: 1991,
        date_of_gp: new Date("2024-06-23"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 11,
        gp_name: "FORMULA 1 QATAR AIRWAYS AUSTRIAN GRAND PRIX 2024",
        track_name: "Red Bull Ring",
        country: "Austria",
        city: "Spielberg",
        circuit_length: 4.318,
        first_gp: 1970,
        date_of_gp: new Date("2024-06-30"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 12,
        gp_name: "FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2024",
        track_name: "Silverstone Circuit",
        country: "United Kingdom",
        city: "Silverstone",
        circuit_length: 5.891,
        first_gp: 1950,
        date_of_gp: new Date("2024-07-07"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 13,
        gp_name: "FORMULA 1 HUNGARIAN GRAND PRIX 2024",
        track_name: "Hungaroring",
        country: "Hungary",
        city: "Budapest",
        circuit_length: 4.381,
        first_gp: 1986,
        date_of_gp: new Date("2024-07-21"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 14,
        gp_name: "FORMULA 1 ROLEX BELGIAN GRAND PRIX 2024",
        track_name: "Circuit de Spa-Francorchamps",
        country: "Belgium",
        city: "Spa",
        circuit_length: 7.004,
        first_gp: 1925,
        date_of_gp: new Date("2024-07-28"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 15,
        gp_name: "FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2024",
        track_name: "Circuit Zandvoort",
        country: "Netherlands",
        city: "Zandvoort",
        circuit_length: 4.259,
        first_gp: 1952,
        date_of_gp: new Date("2024-08-25"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 16,
        gp_name: "FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2024",
        track_name: "Autodromo Nazionale Monza",
        country: "Italy",
        city: "Monza",
        circuit_length: 5.793,
        first_gp: 1921,
        date_of_gp: new Date("2024-09-01"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 17,
        gp_name: "FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX 2024",
        track_name: "Baku City Circu",
        country: "Azerbaijan",
        city: "Baku",
        circuit_length: 6.003,
        first_gp: 2016,
        date_of_gp: new Date("2024-09-15"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 18,
        gp_name: "FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND PRIX 2024",
        track_name: "Marina Bay Street Circuit",
        country: "Singapore",
        city: "Marina Bay",
        circuit_length: 5.063,
        first_gp: 2008,
        date_of_gp: new Date("2024-09-22"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 19,
        gp_name: "FORMULA 1 PIRELLI UNITED STATES GRAND PRIX 2024",
        track_name: "Circuit of The Americas",
        country: "United States",
        city: "Austin",
        circuit_length: 5.513,
        first_gp: 1908,
        date_of_gp: new Date("2024-10-20"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 20,
        gp_name: "FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2024",
        track_name: "Autódromo Hermanos Rodríguez",
        country: "Mexico",
        city: "Mexico City",
        circuit_length: 4.304,
        first_gp: 1962,
        date_of_gp: new Date("2024-10-27"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 21,
        gp_name: "FORMULA 1 LENOVO GRANDE PRÊMIO DE SÃO PAULO 2024",
        track_name: "Autódromo José Carlos Pace",
        country: "Brazil",
        city: "Sao Paulo",
        circuit_length: 4.309,
        first_gp: 1973,
        date_of_gp: new Date("2024-11-03"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 22,
        gp_name: "FORMULA 1 HEINEKEN SILVER LAS VEGAS GRAND PRIX 2024",
        track_name: "Las Vegas Strip Circuit",
        country: "United States",
        city: "Las Vegas",
        circuit_length: 6.1,
        first_gp: 1981,
        date_of_gp: new Date("2024-11-24"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 23,
        gp_name: "FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2024",
        track_name: "Lusail International Circuit",
        country: "Qatar",
        city: "Lusail",
        circuit_length: 5.38,
        first_gp: 2024,
        date_of_gp: new Date("2024-12-01"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
      {
        track_id: 24,
        gp_name: "FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX 2024",
        track_name: "Yas Marina Circuit",
        country: "United Arab Emirates",
        city: "Abu Dhabi",
        circuit_length: 5.554,
        first_gp: 2009,
        date_of_gp: new Date("2024-12-08"),
        gp_header_pic: "",
        gp_track_map1: "",
        gp_track_map2: "",
        gp_pic_1: "",
        gp_pic_2: "",
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("tracks"),
      {
        track_id: [1],
      };
  },
};
