"use strict";

const { query } = require("express");
const driver = require("../models/driver");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("drivers", [
      {
        driver_id: 1,
        driver_name: "Max Verstappen",
        dob: new Date("1997-09-30"),
        country: "Netherlands",
        age: 26,
        f1_team: "Red Bull Racing",
        car_number: 1,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 2,
        driver_name: "Sergio Perez",
        dob: new Date("1990-01-26"),
        country: "Mexico",
        age: 34,
        f1_team: "Red Bull Racing",
        car_number: 11,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 3,
        driver_name: "Lewis Hamilton",
        dob: new Date("1985-01-07"),
        country: "United Kingdom",
        age: 37,
        f1_team: "Mercedes AMG Petronas Formula One Team",
        car_number: 44,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 4,
        driver_name: "George Russell",
        dob: new Date("1998-02-15"),
        country: "United Kingdom",
        age: 24,
        f1_team: "Mercedes AMG Petronas Formula One Team",
        car_number: 63,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 5,
        driver_name: "Charles Leclerc",
        dob: new Date("1997-10-16"),
        country: "Monaco",
        age: 24,
        f1_team: "Scuderia Ferrari",
        car_number: 16,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 6,
        driver_name: "Carlos Sainz Jr",
        dob: new Date("1994-09-01"),
        country: "Spain",
        age: 27,
        f1_team: "Scuderia Ferrari",
        car_number: 55,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 7,
        driver_name: "Lando Norris",
        dob: new Date("1999-11-13"),
        country: "United Kingdom",
        age: 22,
        f1_team: "McLaren F1 Team",
        car_number: 4,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 8,
        driver_name: "Oscar Piastri",
        dob: new Date("2001-04-06"),
        country: "Australia",
        age: 21,
        f1_team: "McLaren F1 Team",
        car_number: 81,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 9,
        driver_name: "Fernando Alonso",
        dob: new Date("1981-07-29"),
        country: "Spain",
        age: 40,
        f1_team: "Aston Martin Cognizant Formula One Team",
        car_number: 14,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 10,
        driver_name: "Lance Stroll",
        dob: new Date("1998-10-29"),
        country: "Canada",
        age: 23,
        f1_team: "Aston Martin Cognizant Formula One Team",
        car_number: 18,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 11,
        driver_name: "Esteban Ocon",
        dob: new Date("1996-09-17"),
        country: "France",
        age: 25,
        f1_team: "Alpine F1 Team",
        car_number: 31,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 12,
        driver_name: "Pierre Gasly",
        dob: new Date("1996-02-07"),
        country: "France",
        age: 26,
        f1_team: "Alpine F1 Team",
        car_number: 10,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 13,
        driver_name: "Valtteri Bottas",
        dob: new Date("1989-08-28"),
        country: "Finland",
        age: 34,
        f1_team: "Stake F1 Team",
        car_number: 77,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 14,
        driver_name: "Zhou Guanyu",
        dob: new Date("1999-05-30"),
        country: "China",
        age: 24,
        f1_team: "Stake F1 Team",
        car_number: 24,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GUAZHO01_Guanyu_Zhou/guazho01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 15,
        driver_name: "Yuki Tsunoda",
        dob: new Date("2000-05-11"),
        country: "Japan",
        age: 23,
        f1_team: "Visa Cash App RB",
        car_number: 22,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/Y/YUKTSU01_Yuki_Tsunoda/yuktsu01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 16,
        driver_name: "Daniel Ricciardo",
        dob: new Date("1989-07-01"),
        country: "Australia",
        age: 32,
        f1_team: "Visa Cash App RB",
        car_number: 3,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/D/DANRIC01_Daniel_Ricciardo/danric01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 17,
        driver_name: "Alex Albon",
        dob: new Date("1996-03-23"),
        country: "Thailand",
        age: 26,
        f1_team: "Williams Racing",
        car_number: 23,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
      {
        driver_id: 18,
        driver_name: "Logan Sargeant",
        dob: new Date("2000-04-30"),
        country: "United States",
        age: 22,
        f1_team: "Williams Racing",
        car_number: 2,
        driver_pic1:
          "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LOGSAR01_Logan_Sargeant/logsar01.png",
        driver_pic2: "",
        driver_pic3: "",
        driver_driving1: "",
        driver_driving2: "",
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("drivers"),
      {
        driver_id: [1],
      };
  },
};
